### PR TITLE
Migrate ci to github actions

### PR DESCRIPTION
**Pull request by arbulu89**
Migrate travis ci to github actions. This 2nd is working much faster than travis ci, and it avoids an external tool usage.

Besides that, I have `tox` usage to run the python unit tests

Besides that, I have added the `_service` file. This makes the packaging in OBS easier. So now on, the package version will be set there instead of directly the spec file.

### CODE REVIEW

**Comment by lpinne** [comment]
Looks good for me.
Thanks!

**Comment by arbulu89** [comment]
@lpinne did you close the PR by accident? We should `merge` instead of `closing` to get the changes to master hehe

**Comment by lpinne** [comment]
Hi Xabier,

> @lpinne <https://github.com/lpinne> did you close the PR by accident? We
> should |merge| instead of |closing| to get the changes to master hehe

oh - I am sorry.
I did not want t o close the PR.

Regards,

Lars

**Review by fmherschel — COMMENTED** [review]
I could not really review your changes according to the test automation as I am not exper in this area.
The changes in the spec file... You set Version and Release to "0" (zero). Is that a special value to link to the _service file where you added the version 0.9.0 (plus the git string= )?

**Review by fmherschel — COMMENTED** [review]
Why do migrate to github actions? Do we migrate from a ci/cd provider to an other? Just like to know what is going around here.

**Review by fmherschel — APPROVED** [review]
@arbulu89 : as already written I am not an expert in migrating ci/cd to github. But in a birds perspective the changes are looking good for me. Maybe you could answer my questions (also internally), if you like. It is for me to learn about your changes.

**Comment by diegoakechi** [comment]
@fmherschel Travis had some recent decisions where the have significantly reduced the amount of capacity dedicated for open source projects, making CI taking sometimes hours to run instead of minutes. We are migrating all of our projects to GH actions as this seems to most reliable option at this point.

**Comment by arbulu89** [comment]
> I could not really review your changes according to the test automation as I am not exper in this area.
> The changes in the spec file... You set Version and Release to "0" (zero). Is that a special value to link to the _service file where you added the version 0.9.0 (plus the git string= )?

I have added `0` value there because the `_service` file will overwrite the value in the package itself. Here the example:
https://build.opensuse.org/package/show/home:xarbulu:sap-deployment/sapstartsrv-resource-agents
The `_service` file is broadly used in OBS as way of versioning the package, as it give the option to automatize many things (adding the git commit sha at the end of the version for example). Summarizing, it is a good practice.

> Why do migrate to github actions? Do we migrate from a ci/cd provider to an other? Just like to know what is going around here.
> You explained that in your first comment, so I precise my question a bit.
> Do we in general move from travis to github or is the first package we are shifting? Just like to know if we are still in the mainstream.

As commented by @diegoakechi travis is having a quite big transition in how they provide their open source services, and the resources quantity has decreased, making the CI execution really slow. Github action are used more and more in open source projects

**Comment by fmherschel** [comment]
@arbulu89 and @diegoakechi thank you for explaining the background. I also have seen that changes on travis and was already wondering if we (SUSE) would react. I like the changes but wanted to know the background.

**Pull request merged**
