### PR TITLE
fix for Issue 9 - SAPStartSrv to translate pgrep returncode into ocf returncodes

### PR DESCRIPTION
**Pull request by fmherschel**

### CODE REVIEW

**Comment by fmherschel** [comment]
@arbulu89 As discussed in the previous PR I have splitted now the fix for the bad return code from the new feature (pre/post service) coming with the next PR

**Review by arbulu89 — CHANGES_REQUESTED** [review]
Hi @fmherschel 
We should put that second big comment in the main docstring.
It makes a visual impresion that the code is splitted.

Besides that, I still see the need to cover this new piece of code by unit test, as the new `if/else` is not.
Let me know if you need any help with the tests

**Comment by fmherschel** [comment]
> Hi @fmherschel
> We should put that second big comment in the main docstring.

??? 

> It makes a visual impresion that the code is splitted.

???
You have asked me to split our previous commits to split the fix of the damaged SAPStartSrv resource agents (bash version did pass the the tests, python version did not)

Now I slipt the PR and you are still blocking my PR which only focusses on the fix of issue_9?

WE NEED TO GET A WORKING PROCESS TO GET THESE FIXES INTO THE GITHUB PROJECT. THE SAP HEC PROJECT IS WAITING TO GET THE ALREADY WORKING CHANGES TO TEST THEM.

I do not any longer to poslish bits and bytes.

Beside that I like to learn about unit tests to get the next component tested LATER(!).

This PR does not inlude the move-service by intention.

> 
> Besides that, I still see the need to cover this new piece of code by unit test, as the new `if/else` is not.
> Let me know if you need any help with the tests

Why are you blocking THIS PR as it does NOT include the new component? It is only a a fix for the already tested
component. BTW: The unit test of SAPStartSrv (python) needs to be improved to test that the function monitor does not
rerurn 1 only if pgrep does not find processes. RC=1 does mean OCF_ERR_GENERIC in the pacemaker cluster and this is FATAL.

**Comment by arbulu89** [comment]
@fmherschel I'm sorry if I gave the impression that I'm blocking your efforts. It was not my intention.
As an "external" contributor who doesn't have that much knowledge about the project, my unique intention was to redirect your changes to follow python best practices.

This just meant:
1. To unify the docstring in method docstring. Something like:
```
def monitor(self):
        '''
        Is the sapstartsrv server process running?

        For regular monitors always return success, because recover of sapstartsrv is already handeled by SAPInstance
        This might be changed in a next-generation edition
        '''

2. To create just one additional UT to cover the 100% of the code.

As they were just small changes, I thought we should add them.

If we have that many urgency, we can just merge this PR, opening a `follow up` github ticket commenting the needed improvements, so we can work on them later. I could do that myself.
Believe me, that everything I try to do is to have the best quality code we can have. Nothing else

**Review by arbulu89 — APPROVED** [review]

**Comment by fmherschel** [comment]
@arbulu89 Thanks for you understanding the pressure. We should have a short call. Lets communcate the other stuff via RC. I was running into the trap mixing the communication channels. Sorry for that.

**Comment by arbulu89** [comment]
Follow up ticket: https://github.com/SUSE/SAPStartSrv-resourceAgent/issues/11

**Pull request merged**
